########################################################################
## Travis CI config for SoapySDR
##
## * matrix tests compilers and build types
## * python bindings built and installed
## * python3 bindings built and installed
## * minimal testing for command line util
## * minimal testing for python bindings
########################################################################

sudo: required
dist: trusty

language: cpp
compiler: gcc

env:
  global:
    - INSTALL_PREFIX=/usr/local
    - PYTHON_EXECUTABLE=/usr/bin/python
    - PYTHON_INSTALL_DIR=lib/python2.7/dist-packages
    - PYTHON3_EXECUTABLE=/usr/bin/python3
    - PYTHON3_INSTALL_DIR=lib/python3/dist-packages
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

# whitelist
branches:
  only:
    - master
    - maint

before_install:
  # regular ubuntu packages
  - sudo add-apt-repository main
  - sudo add-apt-repository universe

  # update after package changes
  - sudo apt-get update

install:

  # install python support dependencies
  - sudo apt-get install -qq python python-dev python-numpy swig

  # install python3 support dependencies
  - sudo apt-get install -qq python3 python3-dev python3-numpy swig

script:
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} -DPYTHON3_EXECUTABLE=${PYTHON3_EXECUTABLE}
  - make
  - sudo make install

  # setup environment paths
  - export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}
  - export PATH=${INSTALL_PREFIX}/bin:${PATH}

  # basic test for command line utility
  - SoapySDRUtil --info
  - SoapySDRUtil --check=null
  - SoapySDRUtil --make="driver=null"

  # basic test for python bindings
  - export PYTHONPATH=${INSTALL_PREFIX}/${PYTHON_INSTALL_DIR}:/usr/${PYTHON_INSTALL_DIR}
  - echo ${PYTHONPATH}
  - ${PYTHON_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.getAPIVersion())"
  - ${PYTHON_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_ABI_VERSION)"
  - ${PYTHON_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_TIMEOUT)"
  - ${PYTHON_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.errToStr(SoapySDR.SOAPY_SDR_TIMEOUT))"
  - ${PYTHON_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.Device.make('driver=null'))"

  # basic test for python3 bindings
  - export PYTHONPATH=${INSTALL_PREFIX}/${PYTHON3_INSTALL_DIR}:/usr/${PYTHON3_INSTALL_DIR}
  - echo ${PYTHONPATH}
  - ${PYTHON3_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.getAPIVersion())"
  - ${PYTHON3_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_ABI_VERSION)"
  - ${PYTHON3_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_TIMEOUT)"
  - ${PYTHON3_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.errToStr(SoapySDR.SOAPY_SDR_TIMEOUT))"
  - ${PYTHON3_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.Device.make('driver=null'))"

  # run unit tests
  - make test

